applicants/urls.py
from django.conf.urls import url
from . import views

app_name = "users"

urlpatterns = [
    url(r'^$', views.login, name='user-login'),
    url(r'^register/$', views.register, name='user-register'),
    url(r'^do_register/$', views.do_register, name='user-do-register'),
    url(r'^view/(?P<index>[A-Za-z0-9]+)/$', views.show, name='show'),
]

companies/urls.py
from django.conf.urls import url
from . import views

app_name = "companies"

urlpatterns = [
    url(r'^$', views.login, name='company-login'),
    url(r'^register/$', views.register, name='company-register'),
    url(r'^do_register/$', views.do_register, name='company-do-register'),
    url(r'^view/(?P<loginID>[A-Za-z0-9]+)/$', views.show, name='show'),
]

msdproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.login, name='main-login'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('applicants.urls')),
    url(r'^companies/', include('companies.urls')),
]

companies/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

companies/views.py
from django.http import HttpResponse
from django.shortcuts import render

def login(request):
    info = {'principal': "Company", 'admin': False, 'action_url': "", 'register_url': "companies:company-register"}
    return render(request, 'users/logins/main_login.html', info)

def register(request):
    info = {'register': True, 'action_url': "companies:company-do-register"}
    return render(request, 'users/logins/register_user.html', info)

def do_register(request):
    # Create a company
    company = Company()
    return HttpResponse(company.title)


def show(request, loginID):
    return HttpResponse(loginID)

companies/templates/companies/header.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/bootstrap.min.css' %}" />
<script type="text/javascript" src="{%  static 'users/js/bootstrap.min.js' %}" ></script>

companies/templates/companies/index.html
{% include "users/header.html" %}

<html>
	<body class="main-body">
		<div class="container">

			<div class="jumbotron">
				<h1>MSD Project</h1>
				<p class="lead">Where companies meet students with Django!!!</p>
				<p>				
					<a href="{% url 'users:user-login' %}"><button class="bigbutton positivebtn">Student Login</button></a>
					<a href="{% url 'users:user-login' %}"><button class="bigbutton positivebtn">Company Login</button></a>
				</p>
			</div>
				
			<footer class="main-footer">
				<p>&copy; 2016 MSDProject, Inc.</p>
			</footer>
		</div>
	</body>
</html>
<!-- &copy; Padmal -->